Repository Miracle-Midnight/Drawing-Duo, pull requests merged in 2023-01, with the labels that each got.

#24 Refactor/ksd/make layout : 전체적인 페이지 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/assets/drawing-duo-logo.png
  frontend/src/assets/voiceoff.png
  frontend/src/components/canvas/canvas.css
  frontend/src/components/canvas/canvas.tsx
  frontend/src/components/userState/userState.css
  frontend/src/components/userState/userState.tsx
  frontend/src/index.css
  frontend/src/routes/gameLobby/gameLobby.css
  frontend/src/routes/gameLobby/gameLobby.tsx
  frontend/src/routes/inGame/inGame.css
  frontend/src/routes/inGame/inGame.tsx
  frontend/src/routes/lobby/lobby.css
  frontend/src/routes/lobby/lobby.tsx
  frontend/src/routes/login/login.css
  frontend/src/routes/login/login.tsx
  frontend/src/routes/register/register.css
  frontend/src/routes/register/register.tsx
  frontend/src/routes/result/result.css
  frontend/src/routes/result/result.tsx
  frontend/tailwind.config.js
  voice-on.svg
Labels: enhancement

#39 Feat/ksd/edit in game layout : 인게임 레이아웃 및 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/chat/chat.tsx
  frontend/src/components/chatList/chatList.tsx
  frontend/src/components/headerNav/header.tsx
  frontend/src/components/hintImage/hintImage.tsx
  frontend/src/components/sideNav/sideNav.tsx
  frontend/src/routes/gameLobby/gameLobby.tsx
  frontend/src/routes/inGame/inGame.tsx
  frontend/src/routes/login/login.tsx
  frontend/src/routes/makeRoom/makeRoom.css
  frontend/src/routes/makeRoom/makeRoom.tsx
  frontend/src/routes/register/register.tsx
Labels: enhancement

#40 Feat/ksd/make friends list : 친구 목록 리스트 컴포넌트 만들기
  frontend/src/components/friendsCard/friendsCard.tsx
  frontend/src/components/friendsCardList/friendsCardList.tsx
  frontend/src/components/headerNav/header.tsx
Labels: enhancement

#50 Feat/ksd/make socket chat
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/image-svgrepo-com (1).svg
  frontend/src/assets/image-svgrepo-com (2).svg
  frontend/src/assets/image-svgrepo.svg
  frontend/src/assets/send-svgrepo-com.svg
  frontend/src/components/chat/chat.tsx
  frontend/src/components/chatList/chatList.tsx
  frontend/src/components/sideNav/sideNav.tsx
Labels: enhancement

#55 Feat/ksd/edit chat layout : 채팅 레이아웃 수정 및 버그 수정
  frontend/src/components/chat/chat.tsx
  frontend/src/components/chatList/chatList.tsx
  frontend/src/components/sideNav/sideNav.tsx
Labels: 🐞bug, ✨ feature

#60 Refactor/ksd/import svg : svg 태그들을 import함
  frontend/src/components/drawTools/eraser.tsx
  frontend/src/components/drawTools/palette.tsx
  frontend/src/components/drawTools/pen.tsx
  frontend/src/components/drawTools/redo.tsx
  frontend/src/components/drawTools/undo.tsx
  frontend/src/components/inputRange/inputRange.tsx
  frontend/src/routes/inGame/inGame.tsx
Labels: 💩wontfix, 🔨refactoring

#62 Feat/ksd/edit game lobby : 게임 로비 화면 내의 사용자 컴포넌트 수정
  frontend/src/components/userState/userState.tsx
  frontend/src/routes/gameLobby/gameLobby.css
  frontend/src/routes/gameLobby/gameLobby.tsx
  frontend/src/routes/inGame/inGame.tsx
Labels: 💩wontfix

#71 Feat/ksd/deploy : 프론트엔드 배포 완료
  frontend/package.json
Labels: ✨ feature

#77 Feat/ksd/make invite friend : 친구 초대, 친구 추가 UI 제작 및 친구 검색 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/friendsCard/friendsCard.tsx
  frontend/src/components/friendsCardList/friendsCardList.css
  frontend/src/components/friendsCardList/friendsCardList.tsx
  frontend/src/components/headerNav/header.tsx
  frontend/src/components/imageCard/imageCard.tsx
  frontend/src/components/modal/modal.tsx
  frontend/src/components/searchInput/searchInput.tsx
  frontend/src/routes/gameLobby/gameLobby.tsx
Labels: ✨ feature, ➕enhancement

#81 Fix/ksd/edit in game margin : 인게임 내의 마진제거
  frontend/src/components/chatList/chatList.tsx
  frontend/src/components/sideNav/sideNav.tsx
  frontend/src/routes/inGame/inGame.tsx
Labels: 🐞bug, ✨ feature

#83 fix/ksd/editChatButton : 채팅 버튼 배경 색 수정
  frontend/src/components/chatList/chatList.tsx
  frontend/src/components/friendsCardList/friendsCardList.css
Labels: 🐞bug, ✨ feature, 💩wontfix

#104 Deploy : github actions 설정
  .github/workflows/frontend-deploy.yml
Labels: 🌏 deploy

#109 Refactor/ksd/seperate component : 컴포넌트 분리 완료
  frontend/src/components/sideNav/sideNav.tsx
  frontend/src/components/sideNav/sideNavAtoms/closeButtonElem/closeButtonElem.tsx
  frontend/src/components/sideNav/sideNavAtoms/hintImageElement/hintImageElement.tsx
  frontend/src/components/sideNav/sideNavAtoms/micElems/micOffElem.tsx
  frontend/src/components/sideNav/sideNavAtoms/micElems/micOnElem.tsx
  frontend/src/components/sideNav/sideNavAtoms/soundElems/soundOffElem.tsx
  frontend/src/components/sideNav/sideNavAtoms/soundElems/soundOnElem.tsx
  frontend/src/components/sideNav/sideNavMolecules/chatOnOffMolecule.tsx
  frontend/src/components/sideNav/sideNavMolecules/imageOnOffMolecules.tsx
  frontend/src/components/sideNav/sideNavMolecules/micOnOffMolecule.tsx
  frontend/src/components/sideNav/sideNavMolecules/soundOnOffMolecule.tsx
  frontend/src/y.ts
Labels: 🔨 refactoring

#116 Fix/ksd/fix pad : 인 게임 각각의 Div 포지션 줄이기
  frontend/check-cloudfront-status.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/drawTools/drawTools.css
  frontend/src/components/drawTools/drawTools.tsx
  frontend/src/components/sideNav/sideNav.tsx
  frontend/src/hooks/useLine.ts
  frontend/src/routes/inGame/inGame.tsx
  frontend/src/y.ts
Labels: 💩 wontfix

#125 Feat/ksd/send drawing data
  frontend/src/components/canvas/ImageCanvas.tsx
  frontend/src/components/canvas/canvas.tsx
  frontend/src/components/closeRoomModal/closeRoomModal.tsx
  frontend/src/components/palette/palette.tsx
  frontend/src/components/sideNav/sideNav.tsx
Labels: ✨ feature

#132 Feat/ksd/edit drawing tools : drawing tools 고정
  frontend/src/components/drawTools/drawTools.tsx
  frontend/src/components/drawTools/eraser.tsx
  frontend/src/components/drawTools/fill.tsx
  frontend/src/components/drawTools/palette.tsx
  frontend/src/components/drawTools/pen.tsx
  frontend/src/components/inputRange/inputRange.tsx
  frontend/src/components/palette/palette.tsx
  frontend/src/components/sideNav/sideNav.tsx
  frontend/src/routes/inGame/inGame.tsx
Labels: ✨ feature, 💩 wontfix, 🎨 style

#140 Style/ksd/edit css : CSS 고침
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/canvas/ImageCanvas.tsx
  frontend/src/components/closeRoomModal/closeRoomModal.tsx
  frontend/src/components/friendsCard/friendsCard.tsx
  frontend/src/components/friendsCardList/friendsCardList.tsx
  frontend/src/components/headerNav/header.tsx
  frontend/src/components/imageList/imageList.tsx
  frontend/src/components/invite/invite.tsx
  frontend/src/components/inviteCardList/inviteCardList.tsx
  frontend/src/components/invitedButton/invitedButton.tsx
  frontend/src/components/invitedCardList/invitedCardList.tsx
  frontend/src/components/logout/logout.tsx
  frontend/src/components/palette/palette.tsx
  frontend/src/components/profile/profile.tsx
  frontend/src/components/searchCard/searchCard.tsx
  frontend/src/components/searchFriendList/searchFriendList.tsx
  frontend/src/components/searchInput/searchInput.tsx
  frontend/src/components/sideNav/sideNav.tsx
  frontend/src/routes/gameLobby/gameLobby.tsx
  frontend/src/routes/inGame/inGame.css
  frontend/src/routes/inGame/inGame.tsx
Labels: 🐞 bug, ✨ feature, 🎨 style

#138 Fix: Fix WebRTC
  backend/src/gateway/room.gateway.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/UserCursor/usercursor.tsx
  frontend/src/components/canvas/ImageCanvas.tsx
  frontend/src/components/card/card.tsx
  frontend/src/components/createRoomModal/createRoomModal.tsx
  frontend/src/components/inviteCardList/inviteCardList.tsx
  frontend/src/components/invitedCard/invitedCard.tsx
  frontend/src/components/userState/userState.tsx
  frontend/src/components/voiceChat/voiceChat.tsx
  frontend/src/hooks/history.ts
  frontend/src/hooks/socket.ts
  frontend/src/index.tsx
  frontend/src/routes/gameLobby/gameLobby.tsx
  frontend/src/routes/intro/intro.tsx
Labels: 🐞 bug
